"""Continuous ESS measurement support for PhaseEQ."""

from .analysis import (
    analyze_shot,
    apply_gate,
    average_responses,
    build_standard_result,
    conservative_denoised_result,
    effective_merge_crossover_hz,
    estimate_clock_drift,
    generate_ess_reference,
    high_precision_result,
    select_ir_center,
    time_align_impulse_to_center,
)
from .engine import ContinuousMeasurementEngine, input_settings_error, list_input_devices, refresh_audio_devices
from .input_gain import InputGainSnapshot, input_gain_is_unchanged, read_input_gain_snapshot, set_input_gain_adjustment
from .noise_preflight import AmbientNoiseProfile, PilotAssessment, assess_pilot, measure_ambient_noise, pilot_snr_thresholds
from .generator import (
    EssGeneratorSettings,
    GeneratedEssBundle,
    GeneratedLevelCheckSignal,
    generate_ess_bundle,
    generate_level_check_signal,
    generate_marker_ess_bundle,
    generate_timing_marker,
    generator_preset,
    ess_generator_rejection_reasons,
)
from .levels import (
    AcousticCalibrationEstimate,
    InputLevelReading,
    capture_input_level,
    estimate_acoustic_calibration,
    level_calibration_offset_db,
    level_calibration_kind,
    response_level_dbfs,
    response_level_spl,
)
from .models import (
    AverageMode,
    HighPrecisionResult,
    MeasurementSettings,
    MeasurementState,
    SessionSnapshot,
    ShotQuality,
    ShotResult,
    ShotStatus,
)
from .persistence import (
    cleanup_measurement_autosave,
    cleanup_unrestorable_measurement_sessions_once,
    export_measurement_session,
    load_measurement_session,
)
from .reference_track import (
    KnownEssReference,
    build_inferred_ess_manifest,
    ess_reference_rejection_reasons,
    extract_known_ess_reference,
    extract_manifest_ess_reference,
    tweeter_reference_routing_rejection_reasons,
)

__all__ = [
    "AverageMode",
    "ContinuousMeasurementEngine",
    "EssGeneratorSettings",
    "GeneratedEssBundle",
    "GeneratedLevelCheckSignal",
    "HighPrecisionResult",
    "InputGainSnapshot",
    "AmbientNoiseProfile",
    "PilotAssessment",
    "pilot_snr_thresholds",
    "KnownEssReference",
    "build_inferred_ess_manifest",
    "InputLevelReading",
    "AcousticCalibrationEstimate",
    "MeasurementSettings",
    "MeasurementState",
    "SessionSnapshot",
    "ShotQuality",
    "ShotResult",
    "ShotStatus",
    "analyze_shot",
    "apply_gate",
    "average_responses",
    "capture_input_level",
    "estimate_acoustic_calibration",
    "cleanup_measurement_autosave",
    "cleanup_unrestorable_measurement_sessions_once",
    "build_standard_result",
    "conservative_denoised_result",
    "effective_merge_crossover_hz",
    "estimate_clock_drift",
    "ess_generator_rejection_reasons",
    "ess_reference_rejection_reasons",
    "tweeter_reference_routing_rejection_reasons",
    "export_measurement_session",
    "extract_known_ess_reference",
    "extract_manifest_ess_reference",
    "generate_ess_reference",
    "generate_ess_bundle",
    "generate_level_check_signal",
    "generate_marker_ess_bundle",
    "generate_timing_marker",
    "generator_preset",
    "high_precision_result",
    "select_ir_center",
    "time_align_impulse_to_center",
    "input_settings_error",
    "level_calibration_offset_db",
    "level_calibration_kind",
    "list_input_devices",
    "input_gain_is_unchanged",
    "load_measurement_session",
    "refresh_audio_devices",
    "read_input_gain_snapshot",
    "set_input_gain_adjustment",
    "assess_pilot",
    "measure_ambient_noise",
    "response_level_dbfs",
    "response_level_spl",
]
