from __future__ import annotations

import io
import hashlib
import json
import re
import zipfile
from datetime import datetime
from typing import Any

import numpy as np

from phase_fir_designer import DesignConfig, IIRFilter, SpeakerResponse
from phase_fir_designer.linear_fir import band_split_iir_filters, band_split_output_auxiliary_sos
from phase_fir_designer.export import export_bin, export_csv, export_txt, export_wav
from phase_fir_designer.export_pipeline import output_fir_for_export_report
from phase_fir_designer.iir import (
    export_biquad_csv,
    export_biquad_json,
    export_iir_parameter_document,
    export_minidsp_biquads,
    export_sigmastudio_biquads,
    export_camilladsp_biquads,
)


def target_response_csv(target: SpeakerResponse) -> str:
    rows = ["frequency,gain_db,phase_deg"]
    for idx, frequency in enumerate(target.frequency):
        if target.phase_deg is None:
            rows.append(f"{frequency},{target.gain_db[idx]},")
        else:
            rows.append(f"{frequency},{target.gain_db[idx]},{target.phase_deg[idx]}")
    return "\n".join(rows) + "\n"


def target_response_txt(target: SpeakerResponse) -> str:
    rows = []
    for idx, frequency in enumerate(target.frequency):
        if target.phase_deg is None:
            rows.append(f"{frequency}\t{target.gain_db[idx]}")
        else:
            rows.append(f"{frequency}\t{target.gain_db[idx]}\t{target.phase_deg[idx]}")
    return "\n".join(rows) + "\n"


def target_response_gain_csv(target: SpeakerResponse) -> str:
    rows = ["frequency,gain_db"]
    for idx, frequency in enumerate(target.frequency):
        rows.append(f"{frequency},{target.gain_db[idx]}")
    return "\n".join(rows) + "\n"


def target_response_gain_txt(target: SpeakerResponse) -> str:
    rows = []
    for idx, frequency in enumerate(target.frequency):
        rows.append(f"{frequency}\t{target.gain_db[idx]}")
    return "\n".join(rows) + "\n"


def target_response_dirac_live(target: SpeakerResponse) -> str:
    pairs = sorted(
        (float(frequency), float(gain))
        for frequency, gain in zip(target.frequency, target.gain_db)
        if np.isfinite(frequency) and np.isfinite(gain) and float(frequency) > 0.0
    )
    if len(pairs) < 2:
        raise ValueError("Dirac Live Targetには2点以上の有効な周波数が必要です。")
    lines = ["# Generated by PhaseEQ", "BREAKPOINTS"]
    lines.extend(f"{frequency:.10g} {gain:.10g}" for frequency, gain in pairs)
    lines.extend(
        [
            "HPSLOPEON", "0", "LPSLOPEON", "0", "HPCUTOFF", f"{pairs[0][0]:.10g}",
            "LPCUTOFF", f"{pairs[-1][0]:.10g}", "HPORDER", "4", "LPORDER", "4",
            "LOWLIMITHZ", f"{pairs[0][0]:.10g}", "HIGHLIMITHZ", f"{pairs[-1][0]:.10g}",
        ]
    )
    return "\n".join(lines) + "\n"


def target_response_from_result(result: Any) -> SpeakerResponse:
    return SpeakerResponse(
        frequency=result.frequency.tolist(),
        gain_db=result.target_gain_db.tolist(),
        phase_deg=result.target_phase_unwrapped_deg.tolist(),
    )


def safe_project_stem(project_name: str, *, fallback: str) -> str:
    normalized = re.sub(r"\s+", "_", str(project_name).strip())
    normalized = re.sub(r"[^0-9A-Za-z._-]+", "_", normalized)
    normalized = normalized.strip("._-")
    return normalized or fallback


def project_file_base(project_name: str, *, app_slug: str, timestamp: datetime | None = None) -> str:
    current_timestamp = timestamp or datetime.now()
    return f"{safe_project_stem(project_name, fallback=app_slug)}_Bundle_{output_timestamp_label(current_timestamp)}"


def output_timestamp_label(timestamp: datetime | None = None) -> str:
    current = timestamp or datetime.now()
    unique = f"{current.microsecond % 4096:03X}"
    return current.strftime("%y%m%d-%H%M") + f"-{unique}"


def sample_rate_label(sample_rate: int) -> str:
    rate = int(sample_rate)
    return f"{rate // 1000}k" if rate % 1000 == 0 else f"{rate}Hz"


def output_file_name(
    project_name: str,
    role: str,
    extension: str,
    *,
    app_slug: str = "phaseeq",
    sample_rate: int | None = None,
    target: str | None = None,
    band: str | None = None,
    timestamp: datetime | None = None,
) -> str:
    parts = [safe_project_stem(project_name, fallback=app_slug)]
    if band:
        parts.append(safe_project_stem(band, fallback="Way"))
    parts.append(safe_project_stem(role, fallback="Output"))
    if target:
        parts.append(safe_project_stem(target, fallback="DSP"))
    if sample_rate is not None:
        parts.append(sample_rate_label(sample_rate))
    parts.append(output_timestamp_label(timestamp))
    return "_".join(parts) + f".{extension.lstrip('.')}"


TARGET_OUTPUT_NAME_PARTS = {
    "target_gain_csv": ("Target-Gain", "csv"),
    "target_gain_txt": ("Target-Gain", "txt"),
    "target_csv": ("Target-GainPhase", "csv"),
    "target_txt": ("Target-GainPhase", "txt"),
    "dirac_live_target": ("Target", "targetcurve"),
}


def target_output_file_name(
    project_name: str,
    format_name: str,
    *,
    app_slug: str = "phaseeq",
    timestamp: datetime | None = None,
    band: str | None = None,
) -> str:
    role, extension = TARGET_OUTPUT_NAME_PARTS[format_name]
    target = "Dirac" if format_name == "dirac_live_target" else None
    return output_file_name(project_name, role, extension, app_slug=app_slug, target=target, band=band, timestamp=timestamp)


def speaker_response_csv(response: SpeakerResponse) -> str:
    rows = ["frequency,gain_db,phase_deg"]
    phase = response.phase_deg if response.phase_deg is not None else [None] * len(response.frequency)
    for frequency, gain, phase_deg in zip(response.frequency, response.gain_db, phase):
        phase_text = "" if phase_deg is None else f"{float(phase_deg):.10g}"
        rows.append(f"{float(frequency):.10g},{float(gain):.10g},{phase_text}")
    return "\n".join(rows) + "\n"


def fir_export_bytes(format_name: str, fir: np.ndarray, sample_rate: int) -> bytes:
    if format_name == "wav":
        buffer = io.BytesIO()
        export_wav(buffer, fir, sample_rate)
        return buffer.getvalue()
    if format_name == "bin":
        buffer = io.BytesIO()
        export_bin(buffer, fir)
        return buffer.getvalue()
    text_buffer = io.StringIO()
    if format_name == "txt":
        export_txt(text_buffer, fir)
    elif format_name == "csv":
        export_csv(text_buffer, fir)
    else:
        raise ValueError(f"unsupported FIR output format: {format_name}")
    return text_buffer.getvalue().encode("utf-8")


def target_export_text(format_name: str, target: SpeakerResponse) -> str:
    if format_name == "dirac_live_target":
        return target_response_dirac_live(target)
    if format_name == "target_gain_csv":
        return target_response_gain_csv(target)
    if format_name == "target_gain_txt":
        return target_response_gain_txt(target)
    if format_name == "target_csv":
        return target_response_csv(target)
    if format_name == "target_txt":
        return target_response_txt(target)
    raise ValueError(f"unsupported Target output format: {format_name}")


def target_export_extension(format_name: str) -> str:
    if format_name == "dirac_live_target":
        return "targetcurve"
    return "txt" if format_name.endswith("_txt") else "csv"


def project_readme_text(
    project_name: str,
    base_name: str,
    *,
    app_name: str,
    app_version: str,
    app_author: str,
    app_slug: str,
) -> str:
    return f"""# PhaseEQ Project Bundle

Project: {project_name or "(no project name)"}
Bundle: {base_name}
App: {app_name} v{app_version}
Author: {app_author}

## Contents

- settings/{app_slug}_settings.json
  - PhaseEQで復元するための設定ファイルです。
  - Speaker/Input、Mic Calibration、Target Responseの数値データも含みます。
- inputs/
  - 読み込み済みのSpeaker/Input、Mic Calibration、Target ResponseをCSV化した控えです。
- outputs/
  - 選択した形式のFIR係数とTarget Responseです。
  - IIR EQがある場合は、FIRとは別にBiquad係数を収録します。

## Restore

PhaseEQの設定管理から、このZIPファイルを読み込むと、
設定値と読み込み済みデータを復元できます。
"""


def build_project_zip(
    *,
    project_name: str,
    base_name: str | None = None,
    settings_payload: dict[str, Any],
    result: Any,
    raw_speaker_response: SpeakerResponse | None,
    mic_cal_response: SpeakerResponse | None,
    raw_target_response: SpeakerResponse | None,
    current_target_response: SpeakerResponse,
    fir_formats: list[str],
    target_formats: list[str],
    sample_rate: int,
    app_name: str,
    app_version: str,
    app_author: str,
    app_slug: str,
    fir_output_format_options: set[str],
    target_output_format_options: set[str],
    iir_filters: list[IIRFilter] | None = None,
    output_fir_polarity_invert: bool = False,
    output_fir_remove_nyquist_enabled: bool = False,
    output_fir_remove_nyquist_strength: float = 1.0,
    output_fir_cosine_taper_enabled: bool = False,
    fir_auto_gain_enabled: bool = True,
    generated_at: datetime | None = None,
    band_name: str = "",
    system_context: dict[str, Any] | None = None,
) -> tuple[str, bytes]:
    generated_at = generated_at or datetime.now()
    base_name = base_name or project_file_base(project_name, app_slug=app_slug, timestamp=generated_at)
    enabled_iir_filters = [item for item in (iir_filters or []) if item.enabled]
    split_config = DesignConfig.from_dict({"sample_rate": sample_rate, "taps": len(result.fir),
                                          **settings_payload.get("config", {})}).normalized()
    split_filters = list(band_split_iir_filters(split_config))
    split_alignment_sos = band_split_output_auxiliary_sos(split_config)
    split_polarity = 1
    if split_config.band_split_recipe is not None:
        from crossover_engine.alignment import output_polarity
        split_polarity = output_polarity(split_config.band_split_recipe)
    output_report = output_fir_for_export_report(
        result.fir,
        output_fir_polarity_invert=output_fir_polarity_invert,
        output_fir_remove_nyquist_enabled=output_fir_remove_nyquist_enabled,
        output_fir_remove_nyquist_strength=output_fir_remove_nyquist_strength,
        output_fir_cosine_taper_enabled=output_fir_cosine_taper_enabled,
        fir_auto_gain_enabled=fir_auto_gain_enabled,
    )
    output_fir = output_report.fir
    auto_gain = output_report.auto_gain
    manifest = {
        "app": app_name,
        "app_version": app_version,
        "project_name": project_name,
        "bundle_name": base_name,
        "fir_output_formats": fir_formats,
        "iir_biquad_outputs": bool(enabled_iir_filters),
        "target_output_formats": target_formats,
        "output_fir_polarity_invert": output_fir_polarity_invert,
        "output_fir_cosine_taper_enabled": output_fir_cosine_taper_enabled,
        "output_fir_cosine_taper_alpha": 0.10,
        "output_fir_remove_nyquist_enabled": output_fir_remove_nyquist_enabled,
        "output_fir_remove_nyquist_strength": output_fir_remove_nyquist_strength,
        "output_fir_removed_nyquist_amplitude": output_report.removed_nyquist_amplitude,
        "fir_auto_gain": {
            "enabled": output_report.auto_gain_enabled,
            "target_peak_db": auto_gain.target_peak_db,
            "attenuation_only": True,
            "oversampling": auto_gain.oversampling,
            "original_peak_db": auto_gain.original_peak_db,
            "output_peak_db": auto_gain.output_peak_db,
            "applied_gain_db": auto_gain.applied_gain_db,
            "linear_gain": auto_gain.linear_gain,
            "fft_size": auto_gain.fft_size,
            "changed": auto_gain.changed,
        },
    }
    buffer = io.BytesIO()
    project_stem = safe_project_stem(project_name, fallback=app_slug)
    package_stamp = output_timestamp_label(generated_at)
    with zipfile.ZipFile(buffer, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        composite_channel_name = " ".join(
            value for value in (project_name.strip(), band_name.strip()) if value
        ) or project_stem
        composite_wav_path = f"composite_input/{project_stem}_FIR_{sample_rate_label(sample_rate)}.wav"
        composite_manifest = {
            "format_version": 2,
            "sample_rate_hz": int(sample_rate),
            "channels": [{
                "name": composite_channel_name,
                "way": band_name.strip() or "Full range",
                "group": "Main",
                "gain": 0.0,
                "polarity": 1,
                "delay": 0.0,
                "wav": composite_wav_path,
                "frd": None,
                "tap_count": int(len(result.fir)),
                "center_position": (int(len(result.fir)) - 1) / 2.0,
                "time_reference": "tap_center",
                "delay_application": "after_center_alignment",
            }],
        }
        archive.writestr(
            "manifest.json",
            json.dumps(composite_manifest, ensure_ascii=False, indent=2, sort_keys=True),
        )
        archive.writestr(
            composite_wav_path,
            fir_export_bytes("wav", np.asarray(result.fir, dtype=float), sample_rate),
        )
        settings_path = f"settings/{project_stem}_Settings_{package_stamp}.json"
        settings_data = json.dumps(
            settings_payload, ensure_ascii=False, indent=2, sort_keys=True,
        ).encode("utf-8")
        archive.writestr(settings_path, settings_data)
        archive.writestr(
            "documentation/portable_restore.json",
            json.dumps({
                "format": "phaseeq-portable-session",
                "format_version": 1,
                "app": app_name,
                "app_version": app_version,
                "settings_path": settings_path,
                "settings_sha256": hashlib.sha256(settings_data).hexdigest(),
                "settings_file_revision": settings_payload.get("settings_file_revision"),
                "settings_schema_version": settings_payload.get("schema_version"),
                "restore_scope": "current_phaseeq_editing_state",
                "excludes": ["measurements_database", "driver_database", "dsp_system_database"],
            }, ensure_ascii=False, indent=2, sort_keys=True),
        )
        archive.writestr(
            f"docs/{project_stem}_Manifest_{package_stamp}.json",
            json.dumps(manifest, ensure_ascii=False, indent=2, sort_keys=True),
        )
        archive.writestr(
            f"docs/{project_stem}_README_{package_stamp}.txt",
            project_readme_text(
                project_name,
                base_name,
                app_name=app_name,
                app_version=app_version,
                app_author=app_author,
                app_slug=app_slug,
            ),
        )
        session_specification = {
            "format": "phaseeq-working-session-specification",
            "format_version": 1,
            "role": "system_channel" if system_context else "standalone",
            "system": dict(system_context or {}),
            "channel": {
                "name": composite_channel_name,
                "band": band_name.strip() or "Full range",
                "sample_rate_hz": int(sample_rate),
                "fir_tap_count": int(len(result.fir)),
                "fir_intrinsic_center_delay_samples": (int(len(result.fir)) - 1) / 2.0,
            },
            "generated_at": generated_at.isoformat(),
        }
        archive.writestr(
            "documentation/session_specification.json",
            json.dumps(session_specification, ensure_ascii=False, indent=2, sort_keys=True),
        )
        if split_filters or split_config.band_split_recipe is not None:
            split_document = (
                "# Output Band Split\n\n"
                f"- LR2 crossover polarity: {split_polarity:+d}\n"
                "- LR2 polarity, manual polarity and All Pass are included in these Biquads. Do not apply a separate polarity inversion.\n"
                "- FIR coefficients do not contain these IIR sections.\n"
                "- Combined chain: IIR EQ, then Output Band Split (HP, LP, alignment).\n"
                "- Acoustic-target All Pass is corrected in FIR and omitted from direct SOS. In v5, LR2 polarity follows the crossover target setting; manual polarity stays direct. Legacy recipes retain their routing. Delay remains in Multiway.\n\n"
                + export_iir_parameter_document(split_filters, sample_rate, extra_sos=split_alignment_sos)
            )
            archive.writestr("documentation/output_band_split.md", split_document)
            if split_config.band_split_recipe is not None:
                archive.writestr("documentation/band_split_recipe.json", json.dumps(
                    split_config.band_split_recipe, ensure_ascii=False, indent=2, allow_nan=False))
            if split_filters or split_alignment_sos.size:
                for role, filters in (("Output-Band-Split", split_filters),
                                      ("Combined-IIR-Chain", [*enabled_iir_filters, *split_filters])):
                    archive.writestr(
                        f"outputs/{output_file_name(project_name, role, 'json', app_slug=app_slug, sample_rate=sample_rate, target='Biquad', band=band_name, timestamp=generated_at)}",
                        export_biquad_json(filters, sample_rate, extra_sos=split_alignment_sos))
        system_label = (
            f"{system_context.get('management_no', '')} · "
            f"rev {system_context.get('revision_number', '')}"
            if system_context else "Standalone PhaseEQ session"
        )
        archive.writestr(
            "documentation/session_specification.md",
            "\n".join((
                "# PhaseEQ Working Session specification",
                "",
                f"- Context: {system_label}",
                f"- Channel: {composite_channel_name}",
                f"- Band: {band_name.strip() or 'Full range'}",
                f"- Sample rate: {int(sample_rate):,} Hz",
                f"- FIR taps: {int(len(result.fir))}",
                f"- FIR intrinsic center delay: {(int(len(result.fir)) - 1) / 2.0:.3f} samples",
                "",
            )),
        )
        if raw_speaker_response is not None:
            archive.writestr(f"inputs/{project_stem}_Input-Speaker_Raw_{package_stamp}.csv", speaker_response_csv(raw_speaker_response))
        if mic_cal_response is not None:
            archive.writestr(f"inputs/{project_stem}_Input-MicCal_Raw_{package_stamp}.csv", speaker_response_csv(mic_cal_response))
        if raw_target_response is not None:
            archive.writestr(f"inputs/{project_stem}_Target_Imported_{package_stamp}.csv", speaker_response_csv(raw_target_response))
        for format_name in fir_formats:
            if format_name in fir_output_format_options:
                archive.writestr(
                    f"outputs/{output_file_name(project_name, 'FIR', format_name, app_slug=app_slug, sample_rate=sample_rate, band=band_name, timestamp=generated_at)}",
                    fir_export_bytes(format_name, output_fir, sample_rate),
                )
        for format_name in target_formats:
            if format_name in target_output_format_options:
                extension = target_export_extension(format_name)
                archive.writestr(
                    f"outputs/{target_output_file_name(project_name, format_name, app_slug=app_slug, band=band_name, timestamp=generated_at)}",
                    target_export_text(format_name, current_target_response),
                )
        if enabled_iir_filters:
            archive.writestr(
                f"outputs/{output_file_name(project_name, 'IIR', 'csv', app_slug=app_slug, sample_rate=sample_rate, target='Biquad', band=band_name, timestamp=generated_at)}",
                export_biquad_csv(enabled_iir_filters, sample_rate),
            )
            archive.writestr(
                f"outputs/{output_file_name(project_name, 'IIR', 'json', app_slug=app_slug, sample_rate=sample_rate, target='Biquad', band=band_name, timestamp=generated_at)}",
                export_biquad_json(enabled_iir_filters, sample_rate),
            )
            archive.writestr(
                f"outputs/{output_file_name(project_name, 'IIR', 'txt', app_slug=app_slug, sample_rate=sample_rate, target='miniDSP', band=band_name, timestamp=generated_at)}",
                export_minidsp_biquads(enabled_iir_filters, sample_rate),
            )
            archive.writestr(
                f"outputs/{output_file_name(project_name, 'IIR', 'txt', app_slug=app_slug, sample_rate=sample_rate, target='SigmaStudio', band=band_name, timestamp=generated_at)}",
                export_sigmastudio_biquads(enabled_iir_filters, sample_rate),
            )
            archive.writestr(
                f"outputs/{output_file_name(project_name, 'IIR', 'yml', app_slug=app_slug, sample_rate=sample_rate, target='CamillaDSP', band=band_name, timestamp=generated_at)}",
                export_camilladsp_biquads(enabled_iir_filters, sample_rate),
            )
        if iir_filters:
            archive.writestr(
                f"outputs/{output_file_name(project_name, 'IIR', 'md', app_slug=app_slug, sample_rate=sample_rate, target='Generic-Parameters', band=band_name, timestamp=generated_at)}",
                export_iir_parameter_document(iir_filters, sample_rate),
            )
    return f"{base_name}.zip", buffer.getvalue()


def config_payload_from_project_zip(file_obj: Any) -> dict[str, Any]:
    data = file_obj.getvalue()
    with zipfile.ZipFile(io.BytesIO(data)) as archive:
        names = archive.namelist()
        settings_names = [
            name for name in names if name.endswith(".json") and ("settings" in name or "config" in name)
        ]
        if not settings_names:
            raise ValueError("ZIP内に設定JSONが見つかりません。")
        portable_name = "documentation/portable_restore.json"
        portable = None
        if portable_name in names:
            portable = json.loads(archive.read(portable_name).decode("utf-8"))
            if portable.get("format") != "phaseeq-portable-session" or int(portable.get("format_version", 0)) != 1:
                raise ValueError("対応していないPhaseEQ Session ZIP形式です。")
        preferred = "settings/phaseeq_settings.json"
        declared = str(portable.get("settings_path", "")) if isinstance(portable, dict) else ""
        settings_name = declared or (preferred if preferred in settings_names else sorted(settings_names)[0])
        if settings_name not in names:
            raise ValueError("ZIP内の復元用設定ファイルが見つかりません。")
        with archive.open(settings_name) as settings_file:
            settings_data = settings_file.read()
        if isinstance(portable, dict):
            expected_hash = str(portable.get("settings_sha256", ""))
            actual_hash = hashlib.sha256(settings_data).hexdigest()
            if not expected_hash or expected_hash != actual_hash:
                raise ValueError("PhaseEQ Session ZIPの設定ファイルが破損または変更されています。")
        return json.loads(settings_data.decode("utf-8"))
