[theme.light]
primaryColor = "#806943"
backgroundColor = "#FAF8F4"
secondaryBackgroundColor = "#F1ECE4"
textColor = "#22252A"
linkColor = "#6D5735"
borderColor = "#D2C8BA"
redColor = "#984B45"
orangeColor = "#98652F"
yellowColor = "#806A38"
greenColor = "#3E6B59"
blueColor = "#365E80"
violetColor = "#68547C"
grayColor = "#5F5A53"
dataframeBorderColor = "#D2C8BA"
dataframeHeaderBackgroundColor = "#E7DFD3"
baseRadius = "6px"
buttonRadius = "6px"
showWidgetBorder = true

[theme.dark]
primaryColor = "#C2A46F"
backgroundColor = "#15181D"
secondaryBackgroundColor = "#20242B"
textColor = "#F3EFE7"
linkColor = "#D4B982"
borderColor = "#454B55"
redColor = "#C9827B"
orangeColor = "#C69A67"
yellowColor = "#BBA267"
greenColor = "#79A991"
blueColor = "#7395B3"
violetColor = "#A997BC"
grayColor = "#B8B0A5"
dataframeBorderColor = "#454B55"
dataframeHeaderBackgroundColor = "#333944"
baseRadius = "6px"
buttonRadius = "6px"
showWidgetBorder = true
